name: Waka Readme

on:
  workflow_dispatch: #for workflow manual trigger
  schedule:
    - cron: '0 17 * * *' # Runs at 12 am Indonesian time (UTC+7)
    
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.2.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: ðŸ”¥
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
